name: shadowsmirrors
favicon: null
layout_spectrum: 0.17669
typography_spectrum: 0.61656
title: 'Shadows & Mirrors | Darkwave Electronic Music For The Underground'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000200'
    - '#fdfffd'
    - '#898379'
    - '#232320'
    - '#686258'
  brandStrength: 0.8459528111852705
  lightness: 0.1567119644023478
  saturation: 0.756847174372524
  rhythmicContrast: 0.7067848870065063
purpose: []
